version: "3.8"

services:
  authphp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authphp-app
    entrypoint: sh .docker/entrypoint.sh
    depends_on:
      authphp-db:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - authphp-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: authphp-db
      DB_PORT: 3306
      DB_DATABASE: authphp
      DB_USERNAME: root
      DB_PASSWORD: root

  authphp-db:
    image: mysql:5.7
    container_name: authphp-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: authphp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - authphp-network

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - authphp-network

networks:
  authphp-network:
    driver: bridge

volumes:
  db_volume: {}